//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalSystem.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueMaster
    {
        public int Id { get; set; }
        public int JournalId { get; set; }
        public string Volume { get; set; }
        public string Issue { get; set; }
        public string Year { get; set; }
        public bool IsCurrent { get; set; }
        public bool IsActive { get; set; }
        public bool IsAhead { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
