//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalSystem.DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AIJDBEntities : DbContext
    {
        public AIJDBEntities()
            : base("name=AIJDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArticlesMaster> ArticlesMasters { get; set; }
        public virtual DbSet<IssueMaster> IssueMasters { get; set; }
        public virtual DbSet<JournalMaster> JournalMasters { get; set; }
    }
}
